create table if not exists public.nfl_ats_grading_lines (
  id bigint generated by default as identity primary key,
  game_id bigint not null
    references public.nfl_games(id)
    on delete cascade,

  external_event_id text not null,
  bookmaker text not null,

  home_team text not null,
  away_team text not null,
  commence_time timestamptz not null,

  home_spread numeric not null,
  away_spread numeric not null,

  market_last_update timestamptz,
  captured_at timestamptz not null default now(),

  created_at timestamptz not null default now(),

  constraint nfl_ats_grading_lines_game_book_unique
    unique (game_id, bookmaker),

  constraint nfl_ats_grading_lines_team_check
    check (home_team <> away_team),

  constraint nfl_ats_grading_lines_spread_check
    check (home_spread = -away_spread)
);

create index if not exists nfl_ats_grading_lines_game_id_idx
  on public.nfl_ats_grading_lines(game_id);

create index if not exists nfl_ats_grading_lines_event_id_idx
  on public.nfl_ats_grading_lines(external_event_id);

alter table public.nfl_ats_grading_lines enable row level security;

create policy "Public read access to NFL ATS grading lines"
  on public.nfl_ats_grading_lines
  for select
  using (true);
