create table if not exists public.nfl_anytime_td_odds (
  id bigint generated by default as identity primary key,

  external_event_id text not null,

  player_name text not null,
  external_player_id text,

  bookmaker text not null,

  yes_price integer,
  no_price integer,

  home_team text not null,
  away_team text not null,
  commence_time timestamptz not null,

  market_last_update timestamptz,
  fetched_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint nfl_anytime_td_odds_event_player_book_unique
    unique (
      external_event_id,
      player_name,
      bookmaker
    )
);

create index if not exists nfl_anytime_td_odds_event_idx
  on public.nfl_anytime_td_odds (
    external_event_id
  );

create index if not exists nfl_anytime_td_odds_player_idx
  on public.nfl_anytime_td_odds (
    public.normalize_nfl_player_name(player_name)
  );

create index if not exists nfl_anytime_td_odds_commence_time_idx
  on public.nfl_anytime_td_odds (
    commence_time
  );

create index if not exists nfl_anytime_td_odds_external_player_idx
  on public.nfl_anytime_td_odds (
    external_player_id
  )
  where external_player_id is not null;
