create table if not exists public.nhl_prop_lines (
  id bigint generated by default as identity primary key,

  event_id text not null,
  commence_time timestamptz not null,
  home_team text not null,
  away_team text not null,

  bookmaker text not null,
  market text not null,

  player_name text not null,
  player_id bigint references public.nhl_players(id)
    on delete set null,

  line numeric not null,
  over_price integer,
  under_price integer,

  bookmaker_last_update timestamptz,
  fetched_at timestamptz not null default now(),
  created_at timestamptz not null default now(),

  constraint nhl_prop_lines_market_check
    check (
      market in (
        'player_shots_on_goal',
        'player_points',
        'player_assists',
        'player_total_saves'
      )
    ),

  constraint nhl_prop_lines_matchup_check
    check (home_team <> away_team)
);

create index if not exists
  nhl_prop_lines_event_idx
on public.nhl_prop_lines(event_id);

create index if not exists
  nhl_prop_lines_player_idx
on public.nhl_prop_lines(player_id);

create index if not exists
  nhl_prop_lines_player_name_idx
on public.nhl_prop_lines(lower(player_name));

create index if not exists
  nhl_prop_lines_market_idx
on public.nhl_prop_lines(market);

create index if not exists
  nhl_prop_lines_event_book_market_idx
on public.nhl_prop_lines(
  event_id,
  bookmaker,
  market
);

create index if not exists
  nhl_prop_lines_commence_time_idx
on public.nhl_prop_lines(commence_time);

alter table public.nhl_prop_lines
  enable row level security;

create policy "Public can read NHL prop lines"
on public.nhl_prop_lines
for select
to anon, authenticated
using (true);
