-- NHL core data model.
-- Canonical player identity is the NHL player ID supplied by the NHL API.

create table public.nhl_games (
  id bigint primary key,
  season integer not null,
  game_type integer not null,
  game_date date not null,
  commence_time timestamptz,
  home_team text not null,
  away_team text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint nhl_games_game_type_check
    check (game_type in (1, 2, 3)),

  constraint nhl_games_team_check
    check (home_team <> away_team)
);

create index nhl_games_game_date_idx
  on public.nhl_games (game_date desc);

create index nhl_games_season_type_idx
  on public.nhl_games (season, game_type, game_date);

create index nhl_games_home_team_idx
  on public.nhl_games (home_team);

create index nhl_games_away_team_idx
  on public.nhl_games (away_team);


create table public.nhl_players (
  id bigint primary key,
  first_name text not null,
  last_name text not null,
  player_name text not null,
  team text not null,
  position text not null,
  sweater_number integer,
  shoots_catches text,
  headshot_url text,
  height_inches integer,
  weight_pounds integer,
  birth_date date,
  birth_city text,
  birth_country text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint nhl_players_position_check
    check (position in ('C', 'L', 'R', 'D', 'G'))
);

create index nhl_players_team_idx
  on public.nhl_players (team);

create index nhl_players_position_idx
  on public.nhl_players (position);

create index nhl_players_name_idx
  on public.nhl_players (lower(player_name));

create table public.nhl_player_game_stats (
  id bigint generated by default as identity primary key,

  game_id bigint not null
    references public.nhl_games(id)
    on delete cascade,

  player_id bigint not null
    references public.nhl_players(id)
    on delete cascade,

  season integer not null,
  game_type integer not null,
  game_date date not null,

  player_name text not null,
  team text not null,
  opponent text not null,
  position text,
  is_home boolean,

  -- Skater statistics
  goals integer,
  assists integer,
  points integer,
  plus_minus integer,
  power_play_goals integer,
  power_play_points integer,
  game_winning_goals integer,
  overtime_goals integer,
  shots integer,
  shifts integer,
  shorthanded_goals integer,
  shorthanded_points integer,
  penalty_minutes integer,
  time_on_ice_seconds integer,

  -- Goalie statistics
  games_started integer,
  decision text,
  shots_against integer,
  goals_against integer,
  saves integer,
  save_percentage numeric,
  shutouts integer,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint nhl_player_game_stats_game_type_check
    check (game_type in (1, 2, 3)),

  constraint nhl_player_game_stats_game_player_unique
    unique (game_id, player_id)
);

create index nhl_player_game_stats_player_date_idx
  on public.nhl_player_game_stats (
    player_id,
    game_date desc
  );

create index nhl_player_game_stats_player_season_idx
  on public.nhl_player_game_stats (
    player_id,
    season,
    game_type,
    game_date desc
  );

create index nhl_player_game_stats_player_opponent_idx
  on public.nhl_player_game_stats (
    player_id,
    opponent,
    game_date desc
  );

create index nhl_player_game_stats_team_date_idx
  on public.nhl_player_game_stats (
    team,
    game_date desc
  );

alter table public.nhl_games enable row level security;
alter table public.nhl_players enable row level security;
alter table public.nhl_player_game_stats enable row level security;

create policy "Public can read NHL games"
  on public.nhl_games
  for select
  to anon, authenticated
  using (true);

create policy "Public can read NHL players"
  on public.nhl_players
  for select
  to anon, authenticated
  using (true);

create policy "Public can read NHL player game stats"
  on public.nhl_player_game_stats
  for select
  to anon, authenticated
  using (true);
