create table if not exists public.nhl_starting_goalies (
  id bigint generated by default as identity primary key,

  game_id bigint not null
    references public.nhl_games(id)
    on delete cascade,

  team text not null,
  opponent text not null,
  is_home boolean not null,

  goalie_id bigint
    references public.nhl_players(id)
    on delete set null,

  goalie_name text,

  status text not null default 'unconfirmed'
    check (status in ('unconfirmed', 'likely', 'confirmed')),

  source text not null default 'daily_faceoff',
  source_goalie_id bigint,
  source_status_id integer,
  source_status text,

  source_updated_at timestamptz,
  source_name text,
  source_url text,
  source_details text,

  game_date date not null,
  commence_time timestamptz not null,

  fetched_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint nhl_starting_goalies_team_opponent_check
    check (team <> opponent),

  constraint nhl_starting_goalies_game_team_unique
    unique (game_id, team)
);

create index if not exists
  nhl_starting_goalies_game_id_idx
  on public.nhl_starting_goalies (game_id);

create index if not exists
  nhl_starting_goalies_goalie_id_idx
  on public.nhl_starting_goalies (goalie_id);

create index if not exists
  nhl_starting_goalies_game_date_idx
  on public.nhl_starting_goalies (game_date);

create index if not exists
  nhl_starting_goalies_commence_time_idx
  on public.nhl_starting_goalies (commence_time);

create index if not exists
  nhl_starting_goalies_status_idx
  on public.nhl_starting_goalies (status);

alter table public.nhl_starting_goalies enable row level security;

drop policy if exists
  "Public read access for NHL starting goalies"
  on public.nhl_starting_goalies;

create policy
  "Public read access for NHL starting goalies"
  on public.nhl_starting_goalies
  for select
  using (true);
