create table if not exists public.nfl_player_game_usage (
  id bigint generated by default as identity primary key,

  external_game_id text not null,
  external_player_id text not null,

  season integer not null,
  week integer not null,
  game_type text,

  player_name text,
  position text,
  team text,
  opponent text,

  offensive_snaps integer,
  offensive_snap_pct numeric,

  carries integer not null default 0,
  targets integer not null default 0,
  receptions integer not null default 0,

  red_zone_carries integer not null default 0,
  red_zone_targets integer not null default 0,

  inside_10_carries integer not null default 0,
  inside_10_targets integer not null default 0,

  inside_5_carries integer not null default 0,
  inside_5_targets integer not null default 0,

  rushing_tds integer not null default 0,
  receiving_tds integer not null default 0,
  total_tds integer not null default 0,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint nfl_player_game_usage_game_player_unique
    unique (external_game_id, external_player_id)
);

create index if not exists nfl_player_game_usage_player_idx
  on public.nfl_player_game_usage (external_player_id);

create index if not exists nfl_player_game_usage_player_season_week_idx
  on public.nfl_player_game_usage (
    external_player_id,
    season,
    week desc
  );

create index if not exists nfl_player_game_usage_team_season_week_idx
  on public.nfl_player_game_usage (
    team,
    season,
    week desc
  );

create index if not exists nfl_player_game_usage_position_season_week_idx
  on public.nfl_player_game_usage (
    position,
    season,
    week desc
  );
