create table if not exists public.nfl_game_odds (
  id bigint generated by default as identity primary key,

  external_event_id text not null,
  bookmaker text not null,

  home_team text not null,
  away_team text not null,
  commence_time timestamptz not null,

  home_spread numeric,
  home_spread_price integer,

  away_spread numeric,
  away_spread_price integer,

  game_total numeric,
  over_price integer,
  under_price integer,

  market_last_update timestamptz,
  fetched_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint nfl_game_odds_event_book_unique
    unique (external_event_id, bookmaker)
);

create index if not exists nfl_game_odds_event_idx
  on public.nfl_game_odds (external_event_id);

create index if not exists nfl_game_odds_commence_idx
  on public.nfl_game_odds (commence_time);

create index if not exists nfl_game_odds_home_team_idx
  on public.nfl_game_odds (home_team);

create index if not exists nfl_game_odds_away_team_idx
  on public.nfl_game_odds (away_team);
