create table if not exists public.nfl_player_identity_aliases (
  id bigint generated by default as identity primary key,
  source text not null,
  source_player_name text not null,
  gsis_id text not null,
  canonical_player_name text not null,
  created_at timestamptz not null default now(),

  constraint nfl_player_identity_aliases_source_name_unique
    unique (source, source_player_name)
);

insert into public.nfl_player_identity_aliases (
  source,
  source_player_name,
  gsis_id,
  canonical_player_name
)
values
  ('the_odds_api', 'Audric Estime', '00-0039373', 'Audric Estimé'),
  ('the_odds_api', 'Drew Ogletree', '00-0037292', 'Andrew Ogletree'),
  ('the_odds_api', 'Hollywood Brown', '00-0035662', 'Marquise Brown'),
  ('the_odds_api', 'James Jordan', '00-0040177', 'Jordan James'),
  ('the_odds_api', 'Joshua Palmer', '00-0036988', 'Josh Palmer'),
  ('the_odds_api', 'Zonovan Knight', '00-0037157', 'Bam Knight')
on conflict (source, source_player_name)
do update set
  gsis_id = excluded.gsis_id,
  canonical_player_name = excluded.canonical_player_name;


create or replace view public.nfl_anytime_td_with_identity as

with roster_players as (
  select distinct
    gsis_id,
    player_name,
    team,
    position,
    public.normalize_nfl_player_name(player_name) as normalized_name
  from public.nfl_player_current_teams
  where season = 2026
),

resolved as (
  select
    c.*,

    coalesce(
      alias_roster.gsis_id,
      exact_roster.gsis_id
    ) as resolved_gsis_id,

    coalesce(
      alias_roster.player_name,
      exact_roster.player_name
    ) as resolved_roster_player_name,

    coalesce(
      alias_roster.team,
      exact_roster.team
    ) as resolved_team,

    coalesce(
      alias_roster.position,
      exact_roster.position
    ) as resolved_position

  from public.nfl_anytime_td_consensus c

  left join public.nfl_player_identity_aliases a
    on a.source = 'the_odds_api'
   and a.source_player_name = c.player_name

  left join roster_players alias_roster
    on alias_roster.gsis_id = a.gsis_id
   and alias_roster.team in (c.home_team, c.away_team)

  left join roster_players exact_roster
    on exact_roster.normalized_name =
       public.normalize_nfl_player_name(c.player_name)
   and exact_roster.team in (c.home_team, c.away_team)
)

select
  external_event_id,
  player_name,

  resolved_gsis_id as external_player_id,
  resolved_roster_player_name as roster_player_name,
  resolved_team as team,
  resolved_position as position,

  away_team,
  home_team,
  commence_time,

  books,
  consensus_probability,
  median_probability,
  lowest_probability,
  highest_probability,

  best_price,
  worst_price,
  market_disagreement,
  latest_fetch

from resolved;
